name: NAMD

on:
  workflow_run:
    workflows: ["Trigger NAMD"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - run: env
